apiVersion: spire.spiffe.io/v1alpha1
kind: ControllerManagerConfig
metadata:
  name: config
metrics:
  bindAddress: ${METRICS_BIND_ADDRESS}
health:
  healthProbeBindAddress: ${HEALTH_PROBE_BIND_ADDRESS}
trustDomain: "${SPIFFE_TRUST_DOMAIN}"
entryIDPrefix: "scm-${INSTANCE}"
clusterName: "scm-${INSTANCE}"
clusterDomain: local
watchClassless: true
spireServerSocketPath: "/var/run/spire/server/sockets/${SYSTEMD_INSTANCE}/private/api.sock"
staticManifestPath: "/etc/spire/server/${SYSTEMD_INSTANCE}/manifests"
logLevel: info
expandEnvStaticManifests: true
