APT::FTPArchive::Release {
  Origin "spire-examples";
  Label "spire-examples";
  Suite "stable";
  Codename "stable";
  Architectures "amd64 arm64";
  Components "main";
  Description "Automated Multi-Arch Repo for spire-examples";
};
